---
title: Merchandising for Power Blog
baseURL: "/"
params:
  layout_style: grid
  palette: black
  header:
    title: blog.MerchandisingForPower
    logo_img: ''
    has_nav: true
  footer:
    content: "&copy; Power Growth Group. All rights reserved."
    links:
    - text: Request Call
      url: https://theproductcoach.typeform.com/to/p1fcTi
      new_window: true
    - text: Power Growth Group
      url: https://www.powergrowthgroup.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
